apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: edu-edu-karaman-utegenov
  labels:
    app: django
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
        environment: production
    spec:
      containers:
      - name: django
        image: docker.io/karaman56/django-k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DEBUG
          value: "FALSE"
        - name: ALLOWED_HOSTS
          value: "*"
        envFrom:
        - secretRef:
            name: django-secrets
        - secretRef:
            name: django-db
