apiVersion: v1
kind: ConfigMap
metadata:
  name: main-nginx-config  # Это имя ConfigMap, с которым работает под
data:
  index.html: |
    <html>
    <body>
    <h1>Привет, это тестовый веб-сервер Караман!</h1>
    </body>
    </html>
