apiVersion: batch/v1
kind: Job
metadata:
  name: django-clearsessions-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: django
        image: django-k8s:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py", "clearsessions"]
        envFrom:
        - secretRef:
            name: django-secrets
  backoffLimit: 0